#!C:\cygwin64\bin\bash

FTVEN_ENV=$1
FTVEN_MODULE=$2
FTVEN_TEAM=$3

if [ ! -f "composer.phar" ]; then
    curl -sS https://getcomposer.org/installer | php
fi

cp app/config/parameters.yml.dist app/config/parameters.yml

rm -rf app/cache/* app/logs/*

php composer.phar install --no-interaction

mkdir -p reports/
rm -rf reports/*
phpunit -c app/ -d zend.enable_gc=0 -d memory_limit=-1 --coverage-clover reports/coverage.xml --coverage-html reports/coverage/ --log-junit reports/junit.xml
bin\phpmd src/ xml app/config/phpmd.xml --reportfile reports/phpmd.xml --exclude=Tests,Test,DataFixtures,Database || true