#!/bin/bash -e

#Get arguments
FTVEN_ENV=$1
FTVEN_MODULE=$2
FTVEN_TEAM=$3

#Get composer
if [ ! -f "composer.phar" ]; then
    curl -sS https://getcomposer.org/installer | php
fi

#Replace parameters variables
cp app/config/parameters.yml.dist app/config/parameters.yml

#Clean cache / logs 
rm -rf app/cache/* app/logs/*

#Install dependencies
php composer.phar install --no-interaction


#Generate reports
mkdir -p reports/
rm -rf reports/*
php bin/phpunit -c app/ -d zend.enable_gc=0 -d memory_limit=-1 --coverage-clover reports/coverage.xml --coverage-html reports/coverage/ --log-junit reports/junit.xml
#php bin/phpcs --report=checkstyle --report-file=reports/phpcs.xml --standard=vendor/instaclick/symfony2-coding-standard/Symfony2/ruleset.xml --extensions=php --ignore=Tests,Test,DataFixtures,Database src/ || true
#php bin/phpcpd --exclude=Tests --exclude=DataFixtures --log-pmd=reports/phpcpd.xml src/ || true
php bin/phpmd src/ xml app/config/phpmd.xml --reportfile reports/phpmd.xml --exclude=Tests,Test,DataFixtures,Database || true
#php bin/pdepend --jdepend-xml=reports/jdepend.xml --jdepend-chart=reports/dependencies.svg --overview-pyramid=reports/overview-pyramid.svg src/
#php bin/phploc --log-xml=reports/phploc.xml src/